apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: examples/helmrepo-hub-channel
  name: nginx-app-sub
  namespace: nginx-app-ns
spec:
  channel: gitops-chn-ns/gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: nginx-pr
