apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-placement
  labels:
    app: nginx-placement
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-placement
  template:
    metadata:
      labels:
        app: nginx-placement
    spec:
      containers:
      - name: nginx
        image: registry.redhat.io/rhel8/nginx-116:latest
        command: ['nginx', '-g', '"daemon off;"']
        ports:
        - containerPort: 8080
