apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx-sub
  namespace: dev
spec:
  channel: dev-helmrepo
  name: nginx-ingress
  placement:
    placementRef:
      kind: PlacementRule
      name: nginx-pr-helmrepo
  packageFilter:
    version: "1.36.3"
  packageOverrides:
  - packageName: nginx-ingress
    packageAlias: nginx-ingress-simple
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          replicaCount: 3
